//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace WebGateway.WS_SP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OCRSPSoap", Namespace="http://tempuri.org/")]
    public partial class OCRSP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTextFromNanoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTextOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OCRSP() {
            this.Url = global::WebGateway.Properties.Settings.Default.WebGateway_WS_SP_OCRSP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTextFromNanoCompletedEventHandler GetTextFromNanoCompleted;
        
        /// <remarks/>
        public event GetTextCompletedEventHandler GetTextCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTextFromNano", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTextFromNano(int[] nanoImg, int w, int h, string token) {
            object[] results = this.Invoke("GetTextFromNano", new object[] {
                        nanoImg,
                        w,
                        h,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTextFromNanoAsync(int[] nanoImg, int w, int h, string token) {
            this.GetTextFromNanoAsync(nanoImg, w, h, token, null);
        }
        
        /// <remarks/>
        public void GetTextFromNanoAsync(int[] nanoImg, int w, int h, string token, object userState) {
            if ((this.GetTextFromNanoOperationCompleted == null)) {
                this.GetTextFromNanoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTextFromNanoOperationCompleted);
            }
            this.InvokeAsync("GetTextFromNano", new object[] {
                        nanoImg,
                        w,
                        h,
                        token}, this.GetTextFromNanoOperationCompleted, userState);
        }
        
        private void OnGetTextFromNanoOperationCompleted(object arg) {
            if ((this.GetTextFromNanoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTextFromNanoCompleted(this, new GetTextFromNanoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetText", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetText([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] rawImage, int w, int h, string token) {
            object[] results = this.Invoke("GetText", new object[] {
                        rawImage,
                        w,
                        h,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTextAsync(byte[] rawImage, int w, int h, string token) {
            this.GetTextAsync(rawImage, w, h, token, null);
        }
        
        /// <remarks/>
        public void GetTextAsync(byte[] rawImage, int w, int h, string token, object userState) {
            if ((this.GetTextOperationCompleted == null)) {
                this.GetTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTextOperationCompleted);
            }
            this.InvokeAsync("GetText", new object[] {
                        rawImage,
                        w,
                        h,
                        token}, this.GetTextOperationCompleted, userState);
        }
        
        private void OnGetTextOperationCompleted(object arg) {
            if ((this.GetTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTextCompleted(this, new GetTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTextFromNanoCompletedEventHandler(object sender, GetTextFromNanoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTextFromNanoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTextFromNanoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTextCompletedEventHandler(object sender, GetTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591