//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ocrdbModel", "FK_Requisicoes_Clientes", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Core.Data.Clientes), "Requisicoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Core.Data.Requisicoes), true)]
[assembly: EdmRelationshipAttribute("ocrdbModel", "FK_ServicosCliente_Clientes", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Core.Data.Clientes), "ServicosCliente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Core.Data.ServicosCliente), true)]
[assembly: EdmRelationshipAttribute("ocrdbModel", "FK_Requisicoes_TipoOCR", "TipoOCR", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Core.Data.TipoOCR), "Requisicoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Core.Data.Requisicoes), true)]
[assembly: EdmRelationshipAttribute("ocrdbModel", "FK_ServicosCliente_Servicos", "Servicos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Core.Data.Servicos), "ServicosCliente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Core.Data.ServicosCliente), true)]

#endregion

namespace Core.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ocrdbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ocrdbEntities object using the connection string found in the 'ocrdbEntities' section of the application configuration file.
        /// </summary>
        public ocrdbEntities() : base("name=ocrdbEntities", "ocrdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ocrdbEntities object.
        /// </summary>
        public ocrdbEntities(string connectionString) : base(connectionString, "ocrdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ocrdbEntities object.
        /// </summary>
        public ocrdbEntities(EntityConnection connection) : base(connection, "ocrdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clientes> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Clientes>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Clientes> _Clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Requisicoes> Requisicoes
        {
            get
            {
                if ((_Requisicoes == null))
                {
                    _Requisicoes = base.CreateObjectSet<Requisicoes>("Requisicoes");
                }
                return _Requisicoes;
            }
        }
        private ObjectSet<Requisicoes> _Requisicoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Servicos> Servicos
        {
            get
            {
                if ((_Servicos == null))
                {
                    _Servicos = base.CreateObjectSet<Servicos>("Servicos");
                }
                return _Servicos;
            }
        }
        private ObjectSet<Servicos> _Servicos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ServicosCliente> ServicosCliente
        {
            get
            {
                if ((_ServicosCliente == null))
                {
                    _ServicosCliente = base.CreateObjectSet<ServicosCliente>("ServicosCliente");
                }
                return _ServicosCliente;
            }
        }
        private ObjectSet<ServicosCliente> _ServicosCliente;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoOCR> TipoOCR
        {
            get
            {
                if ((_TipoOCR == null))
                {
                    _TipoOCR = base.CreateObjectSet<TipoOCR>("TipoOCR");
                }
                return _TipoOCR;
            }
        }
        private ObjectSet<TipoOCR> _TipoOCR;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Requisicoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRequisicoes(Requisicoes requisicoes)
        {
            base.AddObject("Requisicoes", requisicoes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Servicos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToServicos(Servicos servicos)
        {
            base.AddObject("Servicos", servicos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ServicosCliente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToServicosCliente(ServicosCliente servicosCliente)
        {
            base.AddObject("ServicosCliente", servicosCliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoOCR EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoOCR(TipoOCR tipoOCR)
        {
            base.AddObject("TipoOCR", tipoOCR);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ocrdbModel", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clientes object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="token">Initial value of the Token property.</param>
        public static Clientes CreateClientes(global::System.Int32 id, global::System.String nome, global::System.String token)
        {
            Clientes clientes = new Clientes();
            clientes.id = id;
            clientes.Nome = nome;
            clientes.Token = token;
            return clientes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacoes
        {
            get
            {
                return _Observacoes;
            }
            set
            {
                OnObservacoesChanging(value);
                ReportPropertyChanging("Observacoes");
                _Observacoes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacoes");
                OnObservacoesChanged();
            }
        }
        private global::System.String _Observacoes;
        partial void OnObservacoesChanging(global::System.String value);
        partial void OnObservacoesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ocrdbModel", "FK_Requisicoes_Clientes", "Requisicoes")]
        public EntityCollection<Requisicoes> Requisicoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requisicoes>("ocrdbModel.FK_Requisicoes_Clientes", "Requisicoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requisicoes>("ocrdbModel.FK_Requisicoes_Clientes", "Requisicoes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ocrdbModel", "FK_ServicosCliente_Clientes", "ServicosCliente")]
        public EntityCollection<ServicosCliente> ServicosCliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ServicosCliente>("ocrdbModel.FK_ServicosCliente_Clientes", "ServicosCliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ServicosCliente>("ocrdbModel.FK_ServicosCliente_Clientes", "ServicosCliente", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ocrdbModel", Name="Requisicoes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Requisicoes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Requisicoes object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="idCliente">Initial value of the idCliente property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        /// <param name="idOCR">Initial value of the idOCR property.</param>
        /// <param name="captcha">Initial value of the Captcha property.</param>
        /// <param name="resposta">Initial value of the Resposta property.</param>
        public static Requisicoes CreateRequisicoes(global::System.Int32 id, global::System.Int32 idCliente, global::System.DateTime data, global::System.Int32 idOCR, global::System.String captcha, global::System.String resposta)
        {
            Requisicoes requisicoes = new Requisicoes();
            requisicoes.id = id;
            requisicoes.idCliente = idCliente;
            requisicoes.Data = data;
            requisicoes.idOCR = idOCR;
            requisicoes.Captcha = captcha;
            requisicoes.Resposta = resposta;
            return requisicoes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                OnidClienteChanging(value);
                ReportPropertyChanging("idCliente");
                _idCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCliente");
                OnidClienteChanged();
            }
        }
        private global::System.Int32 _idCliente;
        partial void OnidClienteChanging(global::System.Int32 value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.DateTime _Data;
        partial void OnDataChanging(global::System.DateTime value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idOCR
        {
            get
            {
                return _idOCR;
            }
            set
            {
                OnidOCRChanging(value);
                ReportPropertyChanging("idOCR");
                _idOCR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idOCR");
                OnidOCRChanged();
            }
        }
        private global::System.Int32 _idOCR;
        partial void OnidOCRChanging(global::System.Int32 value);
        partial void OnidOCRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Captcha
        {
            get
            {
                return _Captcha;
            }
            set
            {
                OnCaptchaChanging(value);
                ReportPropertyChanging("Captcha");
                _Captcha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Captcha");
                OnCaptchaChanged();
            }
        }
        private global::System.String _Captcha;
        partial void OnCaptchaChanging(global::System.String value);
        partial void OnCaptchaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Resposta
        {
            get
            {
                return _Resposta;
            }
            set
            {
                OnRespostaChanging(value);
                ReportPropertyChanging("Resposta");
                _Resposta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Resposta");
                OnRespostaChanged();
            }
        }
        private global::System.String _Resposta;
        partial void OnRespostaChanging(global::System.String value);
        partial void OnRespostaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mensagem
        {
            get
            {
                return _Mensagem;
            }
            set
            {
                OnMensagemChanging(value);
                ReportPropertyChanging("Mensagem");
                _Mensagem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mensagem");
                OnMensagemChanged();
            }
        }
        private global::System.String _Mensagem;
        partial void OnMensagemChanging(global::System.String value);
        partial void OnMensagemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ocrdbModel", "FK_Requisicoes_Clientes", "Clientes")]
        public Clientes Clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ocrdbModel.FK_Requisicoes_Clientes", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ocrdbModel.FK_Requisicoes_Clientes", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clientes> ClientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ocrdbModel.FK_Requisicoes_Clientes", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clientes>("ocrdbModel.FK_Requisicoes_Clientes", "Clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ocrdbModel", "FK_Requisicoes_TipoOCR", "TipoOCR")]
        public TipoOCR TipoOCR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoOCR>("ocrdbModel.FK_Requisicoes_TipoOCR", "TipoOCR").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoOCR>("ocrdbModel.FK_Requisicoes_TipoOCR", "TipoOCR").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoOCR> TipoOCRReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoOCR>("ocrdbModel.FK_Requisicoes_TipoOCR", "TipoOCR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoOCR>("ocrdbModel.FK_Requisicoes_TipoOCR", "TipoOCR", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ocrdbModel", Name="Servicos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Servicos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Servicos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Servicos CreateServicos(global::System.Int32 id, global::System.String nome)
        {
            Servicos servicos = new Servicos();
            servicos.Id = id;
            servicos.Nome = nome;
            return servicos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sigla
        {
            get
            {
                return _Sigla;
            }
            set
            {
                OnSiglaChanging(value);
                ReportPropertyChanging("Sigla");
                _Sigla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sigla");
                OnSiglaChanged();
            }
        }
        private global::System.String _Sigla;
        partial void OnSiglaChanging(global::System.String value);
        partial void OnSiglaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ocrdbModel", "FK_ServicosCliente_Servicos", "ServicosCliente")]
        public EntityCollection<ServicosCliente> ServicosCliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ServicosCliente>("ocrdbModel.FK_ServicosCliente_Servicos", "ServicosCliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ServicosCliente>("ocrdbModel.FK_ServicosCliente_Servicos", "ServicosCliente", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ocrdbModel", Name="ServicosCliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ServicosCliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ServicosCliente object.
        /// </summary>
        /// <param name="idCliente">Initial value of the IdCliente property.</param>
        /// <param name="idServico">Initial value of the IdServico property.</param>
        /// <param name="limiteConsultasDiarias">Initial value of the LimiteConsultasDiarias property.</param>
        public static ServicosCliente CreateServicosCliente(global::System.Int32 idCliente, global::System.Int32 idServico, global::System.Int32 limiteConsultasDiarias)
        {
            ServicosCliente servicosCliente = new ServicosCliente();
            servicosCliente.IdCliente = idCliente;
            servicosCliente.IdServico = idServico;
            servicosCliente.LimiteConsultasDiarias = limiteConsultasDiarias;
            return servicosCliente;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdServico
        {
            get
            {
                return _IdServico;
            }
            set
            {
                if (_IdServico != value)
                {
                    OnIdServicoChanging(value);
                    ReportPropertyChanging("IdServico");
                    _IdServico = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdServico");
                    OnIdServicoChanged();
                }
            }
        }
        private global::System.Int32 _IdServico;
        partial void OnIdServicoChanging(global::System.Int32 value);
        partial void OnIdServicoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LimiteConsultasDiarias
        {
            get
            {
                return _LimiteConsultasDiarias;
            }
            set
            {
                OnLimiteConsultasDiariasChanging(value);
                ReportPropertyChanging("LimiteConsultasDiarias");
                _LimiteConsultasDiarias = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LimiteConsultasDiarias");
                OnLimiteConsultasDiariasChanged();
            }
        }
        private global::System.Int32 _LimiteConsultasDiarias;
        partial void OnLimiteConsultasDiariasChanging(global::System.Int32 value);
        partial void OnLimiteConsultasDiariasChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ocrdbModel", "FK_ServicosCliente_Clientes", "Clientes")]
        public Clientes Clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ocrdbModel.FK_ServicosCliente_Clientes", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ocrdbModel.FK_ServicosCliente_Clientes", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clientes> ClientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ocrdbModel.FK_ServicosCliente_Clientes", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clientes>("ocrdbModel.FK_ServicosCliente_Clientes", "Clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ocrdbModel", "FK_ServicosCliente_Servicos", "Servicos")]
        public Servicos Servicos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Servicos>("ocrdbModel.FK_ServicosCliente_Servicos", "Servicos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Servicos>("ocrdbModel.FK_ServicosCliente_Servicos", "Servicos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Servicos> ServicosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Servicos>("ocrdbModel.FK_ServicosCliente_Servicos", "Servicos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Servicos>("ocrdbModel.FK_ServicosCliente_Servicos", "Servicos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ocrdbModel", Name="TipoOCR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoOCR : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoOCR object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static TipoOCR CreateTipoOCR(global::System.Int32 id, global::System.String nome)
        {
            TipoOCR tipoOCR = new TipoOCR();
            tipoOCR.id = id;
            tipoOCR.Nome = nome;
            return tipoOCR;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ocrdbModel", "FK_Requisicoes_TipoOCR", "Requisicoes")]
        public EntityCollection<Requisicoes> Requisicoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Requisicoes>("ocrdbModel.FK_Requisicoes_TipoOCR", "Requisicoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Requisicoes>("ocrdbModel.FK_Requisicoes_TipoOCR", "Requisicoes", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
