//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace TestesManuais.GatewayLocal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GatewaySoap", Namespace="http://tempuri.org/")]
    public partial class Gateway : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTextOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTextFromZipOperationCompleted;
        
        private System.Threading.SendOrPostCallback WakeUpOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Gateway() {
            this.Url = global::TestesManuais.Properties.Settings.Default.ClientePost_GatewayLocal_Gateway;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTextCompletedEventHandler GetTextCompleted;
        
        /// <remarks/>
        public event GetTextFromZipCompletedEventHandler GetTextFromZipCompleted;
        
        /// <remarks/>
        public event WakeUpCompletedEventHandler WakeUpCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetText", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetText(string Servico, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] Imagem, int w, int h, string Token) {
            object[] results = this.Invoke("GetText", new object[] {
                        Servico,
                        Imagem,
                        w,
                        h,
                        Token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTextAsync(string Servico, byte[] Imagem, int w, int h, string Token) {
            this.GetTextAsync(Servico, Imagem, w, h, Token, null);
        }
        
        /// <remarks/>
        public void GetTextAsync(string Servico, byte[] Imagem, int w, int h, string Token, object userState) {
            if ((this.GetTextOperationCompleted == null)) {
                this.GetTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTextOperationCompleted);
            }
            this.InvokeAsync("GetText", new object[] {
                        Servico,
                        Imagem,
                        w,
                        h,
                        Token}, this.GetTextOperationCompleted, userState);
        }
        
        private void OnGetTextOperationCompleted(object arg) {
            if ((this.GetTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTextCompleted(this, new GetTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTextFromZip", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTextFromZip(string servico, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] zip, int w, int h, string token) {
            object[] results = this.Invoke("GetTextFromZip", new object[] {
                        servico,
                        zip,
                        w,
                        h,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTextFromZipAsync(string servico, byte[] zip, int w, int h, string token) {
            this.GetTextFromZipAsync(servico, zip, w, h, token, null);
        }
        
        /// <remarks/>
        public void GetTextFromZipAsync(string servico, byte[] zip, int w, int h, string token, object userState) {
            if ((this.GetTextFromZipOperationCompleted == null)) {
                this.GetTextFromZipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTextFromZipOperationCompleted);
            }
            this.InvokeAsync("GetTextFromZip", new object[] {
                        servico,
                        zip,
                        w,
                        h,
                        token}, this.GetTextFromZipOperationCompleted, userState);
        }
        
        private void OnGetTextFromZipOperationCompleted(object arg) {
            if ((this.GetTextFromZipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTextFromZipCompleted(this, new GetTextFromZipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WakeUp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WakeUp() {
            object[] results = this.Invoke("WakeUp", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WakeUpAsync() {
            this.WakeUpAsync(null);
        }
        
        /// <remarks/>
        public void WakeUpAsync(object userState) {
            if ((this.WakeUpOperationCompleted == null)) {
                this.WakeUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWakeUpOperationCompleted);
            }
            this.InvokeAsync("WakeUp", new object[0], this.WakeUpOperationCompleted, userState);
        }
        
        private void OnWakeUpOperationCompleted(object arg) {
            if ((this.WakeUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WakeUpCompleted(this, new WakeUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTextCompletedEventHandler(object sender, GetTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTextFromZipCompletedEventHandler(object sender, GetTextFromZipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTextFromZipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTextFromZipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void WakeUpCompletedEventHandler(object sender, WakeUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WakeUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WakeUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591